# Generated by Django 4.2.9 on 2026-02-10 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_0', models.CharField(max_length=50, null=True)),
                ('name_1', models.CharField(max_length=50, null=True)),
                ('name_2', models.CharField(max_length=50, null=True)),
                ('name_3', models.CharField(max_length=50, null=True)),
                ('type_3', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'Pak_District_Boundary',
                'ordering': ['name_2'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='school',
            name='province',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.district'),
        ),
    ]
