# Generated by Django 4.2.9 on 2026-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_district_remove_school_province_delete_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='establishment_year',
            field=models.IntegerField(blank=True, help_text='Year the school was established', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='has_computer_lab',
            field=models.BooleanField(default=False, help_text='Does the school have a computer lab?'),
        ),
        migrations.AddField(
            model_name='school',
            name='has_library',
            field=models.BooleanField(default=False, help_text='Does the school have a library?'),
        ),
        migrations.AddField(
            model_name='school',
            name='has_playground',
            field=models.BooleanField(default=False, help_text='Does the school have a playground?'),
        ),
        migrations.AddField(
            model_name='school',
            name='num_classrooms',
            field=models.IntegerField(default=0, help_text='Total number of classrooms'),
        ),
        migrations.AddField(
            model_name='school',
            name='num_students',
            field=models.IntegerField(default=0, help_text='Total number of students'),
        ),
        migrations.AddField(
            model_name='school',
            name='num_teachers',
            field=models.IntegerField(default=0, help_text='Total number of teachers'),
        ),
    ]
